# Generated by Django 6.0.4 on 2026-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(help_text='e.g., /static/images/img1.png', max_length=255)),
                ('is_bestseller', models.BooleanField(default=False)),
            ],
        ),
    ]
