# Generated by Django 6.0.4 on 2026-05-29 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('half', 'Half Advance Payment')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='awaiting_confirmation', max_length=32),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flat_no',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
